security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_RETAILER_HQ:          ROLE_USER
        ROLE_RETAILER_ADMIN:       ROLE_RETAILER_HQ
        ROLE_SUPER_ADMIN:          ROLE_RETAILER_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                username_parameter:       username
                password_parameter:       password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/api
            stateless: true
            lexik_jwt: ~

    access_control:
        - { path: ^/api/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_RETAILER_ADMIN, methods: [DELETE] }
        - { path: ^/api/doc, roles: ROLE_RETAILER_ADMIN }
        - { path: ^/api/users, roles: ROLE_RETAILER_ADMIN }
        - { path: ^/api/stores, roles: ROLE_RETAILER_ADMIN, methods: [POST,PUT,DELETE] }
        - { path: ^/api/zones, roles: ROLE_RETAILER_ADMIN, methods: [POST,PUT,DELETE] }
        - { path: ^/api/store_types, roles: ROLE_RETAILER_ADMIN, methods: [POST,PUT,DELETE] }
        - { path: ^/api/device_types, roles: ROLE_RETAILER_ADMIN, methods: [POST,PUT,DELETE] }
        - { path: ^/api/rfid_log_types, roles: ROLE_RETAILER_ADMIN, methods: [POST,PUT,DELETE] }
        - { path: ^/api/zone_types, roles: ROLE_RETAILER_ADMIN, methods: [POST,PUT,DELETE] }
        - { path: ^/api/locations, roles: ROLE_RETAILER_ADMIN, methods: [POST,PUT,DELETE] }
        - { path: ^/api/products, roles: ROLE_RETAILER_ADMIN, methods: [POST,PUT,DELETE] }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
