<?php

namespace RfidBundle\Entity;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RfidLogRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Retrive the older enabled log with the same EPC
     */
    public function getOlderEnabledByEpc(RfidLog $rfidLog)
    {
        $queryBuilder = $this
            ->createQueryBuilder('rl')
            ->where('rl.epc = :epc')
            ->andWhere('rl.enabled = true')
            ->andWhere('rl.timeStamp <= :timeStamp')
            ->setParameter('epc', $rfidLog->getEpc())
            ->setParameter('timeStamp', $rfidLog->getTimeStamp())
        ;
        $olderEnabled = $queryBuilder->getQuery()->getOneOrNullResult();
        return $olderEnabled;
    }
    /**
     * Retrive the enabled log with the same EPC
     */
    public function getEnabledByEpc(RfidLog $rfidLog)
    {
        $queryBuilder = $this
            ->createQueryBuilder('rl')
            ->where('rl.epc = :epc')
            ->andWhere('rl.enabled = true')
            ->setParameter('epc', $rfidLog->getEpc())
        ;
        $enabled = $queryBuilder->getQuery()->getOneOrNullResult();
        return $enabled;
    }
}
